vversion: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Ambiente pronto com Node.js 18"

  pre_build:
    commands:
      - echo "Instalando dependências..."
      - npm install

  build:
    commands:
      - echo "Build iniciado em $(date)"
      - npm run build

  post_build:
    commands:
      - echo "Build finalizado em $(date)"

artifacts:
  files:
    - build/**/*
    - appspec.yml
    - Scripts/**/*





