version: 0.2

env:
  shell: bash

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Preparando ambiente..."
  pre_build:
    commands:
      - echo "Instalando dependências..."
      - npm install
  build:
    commands:
      - echo "Build iniciado em $(date)"
      - npm run build
  post_build:
    commands:
      - echo "Build finalizado em $(date)"

artifacts:
  files:
    - build/**/*
    - appspec.yml
    - Scripts/**/*


